# Testing NumPy's capabilities

## Vectorisation

In [1]:
# Vectorisation is crucial for pandas, and NumPy is in charge of it
import numpy as np

In [2]:
array = np.arange(10, dtype="int32")

In [3]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [4]:
# Thanks to vectorisation, we don't need to iterate through each element
# Instead we just do the operation we want
array += 1

In [5]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

## Overflow

Given that NumPy mimics C in terms of the way it stores numbers, it may have overflows
This means that the size of numbers needs to be specified

In [6]:
n1 = np.array([1], dtype="uint8")
n255 = np.array([255], dtype="uint8")

In [7]:
# Getting an overflow
n1 + n255

array([0], dtype=uint8)

## Missing Values

If there are missing values in the array, those will be converted to NaN (not a number)
and the array type will be changed to floating-point

In [8]:
demo = np.array([1, 2, 3, np.nan])
demo

array([ 1.,  2.,  3., nan])

In [9]:
demo.dtype

dtype('float64')